/**
 * Created by mrahman on 2020-08-13.
 */

global class InvoiceQueryWrapper {
        Public String Entity;
        Public String Branch_Code;
        Public String Branch_Name;
        Public String Acc_No;
        Public String Client;
        Public Datetime Invoice_Date;
        Public Datetime Due_Date;
        Public String Invoice_Number;
        Public String Query_Value;
        Public Datetime Date_Raised;
        Public String Age_of_Query;
        Public String Contact;
        Public String Status;
        Public String Query_Description;
        Public String Comment;
}