@isTest
public class Testwebservice
{
    public static testmethod void testweb()
    {
    test.startTest();
    WebserviceclassCapita.Capitabatch();
    test.stopTest();
    }
     public static testmethod void testweb1()
    {
    test.startTest();
    WebserviceclassCapita.Netivebatch();
    test.stopTest();
    }
    public static testmethod void SiteUpdatebatch1()
    {
    test.startTest();
    WebserviceclassCapita.SiteUpdatebatch();
    test.stopTest();
    }
    public static testmethod void topzUpdatebatch1()
    {
    test.startTest();
    WebserviceclassCapita.TopazUpdatebatch();
    test.stopTest();
    }
    public static testmethod void LTDCompanyUpdatebatch1()
    {
    test.startTest();
    WebserviceclassCapita.LTDCompanyUpdatebatch();
    test.stopTest();
    }
    public static testmethod void PlacementUpdatebatch1()
    {
    test.startTest();
    WebserviceclassCapita.PlacementUpdatebatch();
    test.stopTest();
    }
    public static testmethod void UmbrellaListUpdatebatch1()
    {
    test.startTest();
    WebserviceclassCapita.UmbrellaListUpdatebatch();
    test.stopTest();
    }
}