import { createElement } from 'lwc';
import PortalV2VMSClientJobOrder from 'c/portalV2VMSClientJobOrder';

describe('c-portal-v-2-vms-client-job-order', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-portal-v-2-vms-client-job-order', {
            is: PortalV2VMSClientJobOrder
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});