public class PropertyTreeSearchResponseWrapper{
    public String compliance_id;
	public String category_id;
	public String management_id;
	public String owner_id;
	public String serviced_by_creditor_id;
	public String expiry_date;
	public String reminder_date;
	public String managed_by;
	public String status;
	public String category_name;
	public String property_compliance_detail_type;
	public String owner_name;
	public String serviced_by_creditor_name;

}